version: "3.1"

services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: lineme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "4998:5432"
